# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5f0TElRluB0-Dm2XtEfCCmVPf6JB_tU
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

# --------------- Load Data -----------------
DATA_PATH = "Copy of Last mile Delivery Data.csv"

@st.cache_data
def load_data():
    df = pd.read_csv(DATA_PATH)
    df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

    # Clean numeric columns
    df["delivery_time"] = pd.to_numeric(df["delivery_time"], errors="coerce")
    df["agent_age"] = pd.to_numeric(df["agent_age"], errors="coerce")
    df["agent_rating"] = pd.to_numeric(df["agent_rating"], errors="coerce")

    # Fill missing values
    num_cols = ["delivery_time", "agent_age", "agent_rating"]
    cat_cols = ["weather", "traffic", "vehicle", "area", "category"]

    for col in num_cols:
        df[col] = df[col].fillna(df[col].median())
    for col in cat_cols:
        df[col] = df[col].fillna(df[col].mode()[0])

    # Derived columns
    mean_time = df["delivery_time"].mean()
    std_time = df["delivery_time"].std()
    df["late"] = df["delivery_time"] > (mean_time + std_time)

    def age_group(age):
        if age < 25:
            return "Under 25"
        elif age <= 40:
            return "25–40"
        else:
            return "40+"
    df["age_group"] = df["agent_age"].apply(age_group)

    return df

df = load_data()

# --------------- Dashboard UI -----------------
st.title("📦 Last-Mile Delivery Data Dashboard")
st.markdown("Analyze delivery performance, vehicle efficiency, and delay factors.")

st.sidebar.header("🔍 Filters")
weather = st.sidebar.multiselect("Weather", df["weather"].unique(), df["weather"].unique())
traffic = st.sidebar.multiselect("Traffic", df["traffic"].unique(), df["traffic"].unique())
vehicle = st.sidebar.multiselect("Vehicle", df["vehicle"].unique(), df["vehicle"].unique())
area = st.sidebar.multiselect("Area", df["area"].unique(), df["area"].unique())
category = st.sidebar.multiselect("Category", df["category"].unique(), df["category"].unique())

filtered = df[
    (df["weather"].isin(weather)) &
    (df["traffic"].isin(traffic)) &
    (df["vehicle"].isin(vehicle)) &
    (df["area"].isin(area)) &
    (df["category"].isin(category))
]

# KPIs
col1, col2, col3 = st.columns(3)
col1.metric("Avg Delivery Time (min)", f"{filtered['delivery_time'].mean():.2f}")
col2.metric("Avg Agent Rating", f"{filtered['agent_rating'].mean():.2f}")
col3.metric("Late Deliveries (%)", f"{filtered['late'].mean() * 100:.2f}")

# Visuals
st.subheader("⏳ Delay Analyzer – Weather vs Traffic")
delay_df = filtered.groupby(["weather", "traffic"], as_index=False)["delivery_time"].mean()
st.plotly_chart(px.bar(delay_df, x="traffic", y="delivery_time", color="weather", barmode="group"))

st.subheader("🚗 Vehicle Comparison")
vehicle_df = filtered.groupby("vehicle", as_index=False)["delivery_time"].mean()
st.plotly_chart(px.bar(vehicle_df, x="vehicle", y="delivery_time"))

st.subheader("👤 Agent Performance")
st.plotly_chart(px.scatter(filtered, x="agent_rating", y="delivery_time", color="age_group"))

st.subheader("📍 Area Analysis")
area_df = filtered.groupby("area", as_index=False)["delivery_time"].mean()
st.plotly_chart(px.bar(area_df, x="area", y="delivery_time"))

st.subheader("📦 Category Visualizer")
st.plotly_chart(px.box(filtered, x="category", y="delivery_time"))

st.markdown("**Developed by Abhinav Chanakya — IBCP AI CRS FA-2 Project**")
